// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXxZalhnfAqclKI00t1QEAjsoVOmEw0uM',
    appId: '1:883792984312:web:ceb01511fe637c5aeea30d',
    messagingSenderId: '883792984312',
    projectId: 'cloud-noodle-bar',
    authDomain: 'cloud-noodle-bar.firebaseapp.com',
    storageBucket: 'cloud-noodle-bar.appspot.com',
    measurementId: 'G-QSPCL164PL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2nDE_pnBL1EfcLFYqDe29Ziq6wOmzjRw',
    appId: '1:883792984312:ios:6383066bc4bc1c7deea30d',
    messagingSenderId: '883792984312',
    projectId: 'cloud-noodle-bar',
    storageBucket: 'cloud-noodle-bar.appspot.com',
    iosClientId: '883792984312-cl03m4qd2at09nh6p294q8n5dojsc0ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudnoodlebar',
  );
}
